export const projects = [
    {
        id: 1,
        title: "ASA PH Microfinance System",
        desc: "[Backend] ASA Microdinance system is a web app to manage the company's operation from registration of new members, approval and disbursement of loans, collection of loan payments including rebates, discounts, savings interest. This web app also used for the monitoring of daily collections and reports from branch level to regional level.",
        tech: "NodeJs, ExpressJs, ReactJs, TailwindCSS, MySQL, GCP - Pub/Sub, GCP -Cloud Functions",
        link: "https://www.asaphil.org/",
        role: "FullStack",
    },
    {
        id: 2,
        title: "JC Portal",
        desc: "JC Portal is a web app where JC Premiere's distrutors can view their accounts to monitor their earnings, avail exclusive promos, encash their commissions and shop for products.",
        tech: "PHP, Codeigniter, Jquery, Bootstrap, MySQL, AWS-S3, AWS-EC2",
        link: "https://portal.jcpremiere.com/",
        role: "FullStack",
    },
    {
        id: 3,
        title: "JC Admin (ERP/CMS)",
        desc: "JC Admin is ther admin part of the JC Portal and serves as ERP of JC Premiere. It is a web app that manages the whole JC operations from tracking its inventory to fullfillment of orders, delivery and generation of reports",
        tech: "PHP, Codeigniter, Jquery, Bootstrap, MySQL, AWS-S3, AWS-EC2",
        link: "https://jcpremiere.com/",
        role: "FullStack",
    },
    {
        id: 4,
        title: "JCW Franchising Admin (ERP/CMS)",
        desc: "JCW Franchising is a food franchising company. This web app serves as the admin  and ERP of the JCW Franchising. Admin can manage their franchisees, new applicants, product inventory, orders, delivery and generation of reports",
        tech: "PHP, Codeigniter, Jquery, Bootstrap, MySQL, AWS-S3, AWS-EC2",
        link: "https://houseoffranchiseinc.com/hof/",
        role: "FullStack",
    },
    {
        id: 5,
        title: "ToktokWallet",
        desc: "[Backend] Toktokwallet is an e-wallet app inside of Toktok App. You can use it to pay services, bills, buy loads, and many more. You can cash-in thru online banks, credit cards and OTC. It is similar to other e-wallet apps like G-cash, Coins.ph, Maya and other",
        tech: "GraphQL, NodeJs, MySQL",
        link: "https://wallet.toktok.ph/",
        role: "Backend",
    },
];
